apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildmart-bff
  namespace: buildmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildmart-bff
  template:
    metadata:
      labels:
        app: buildmart-bff
    spec:
      containers:
        - name: buildmart-bff
          image: buildmart-bff:latest
          ports:
            - containerPort: 8084
          env:
            - name: ip_port_materials
              value: buildmart-materials:8001
            - name: ip_port_workers
              value: buildmart-workers:8002
            - name: ip_port_delivery
              value: buildmart-delivery:8003
          livenessProbe:
            httpGet:
              path: /buildmart-bff/common/health
              port: 8084
          readinessProbe:
            httpGet:
              path: /buildmart-bff/common/health
              port: 8084
