version: "3.8"

services:
  buildmart-materials:
    build:
      context: ./core
      dockerfile: buildmart-materials/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - buildmart-net

  buildmart-workers:
    build:
      context: ./core
      dockerfile: buildmart-workers/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - buildmart-net

  buildmart-delivery:
    build:
      context: ./core
      dockerfile: buildmart-delivery/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - buildmart-net

  buildmart-bff:
    build:
      context: ./bff
      dockerfile: buildmart-bff/Dockerfile
    ports:
      - "8084:8084"
    environment:
      ip_port_materials: buildmart-materials:8001
      ip_port_workers: buildmart-workers:8002
      ip_port_delivery: buildmart-delivery:8003
    depends_on:
      - buildmart-materials
      - buildmart-workers
      - buildmart-delivery
    networks:
      - buildmart-net

networks:
  buildmart-net:
    driver: bridge
