version: "3.8"

services:
  buildmart-materials:
    image: ghcr.io/sandeep8756/buildmart-materials:latest
    ports:
      - "8001:8001"
    networks:
      - buildmart-net

  buildmart-workers:
    image: ghcr.io/sandeep8756/buildmart-workers:latest
    ports:
      - "8002:8002"
    networks:
      - buildmart-net

  buildmart-delivery:
    image: ghcr.io/sandeep8756/buildmart-delivery:latest
    ports:
      - "8003:8003"
    networks:
      - buildmart-net

  buildmart-materials-bff:
    image: ghcr.io/sandeep8756/buildmart-materials-bff:latest
    ports:
      - "8101:8101"
    environment:
      ip_port: buildmart-materials:8001
    depends_on:
      - buildmart-materials
    networks:
      - buildmart-net

  buildmart-workers-bff:
    image: ghcr.io/sandeep8756/buildmart-workers-bff:latest
    ports:
      - "8102:8102"
    environment:
      ip_port: buildmart-workers:8002
    depends_on:
      - buildmart-workers
    networks:
      - buildmart-net

  buildmart-delivery-bff:
    image: ghcr.io/sandeep8756/buildmart-delivery-bff:latest
    ports:
      - "8103:8103"
    environment:
      ip_port: buildmart-delivery:8003
    depends_on:
      - buildmart-delivery
    networks:
      - buildmart-net

networks:
  buildmart-net:
    driver: bridge
