services:
  materials-service:
    build:
      context: .
      dockerfile: core/materials-service/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - buildmart-net

  workers-service:
    build:
      context: .
      dockerfile: core/workers-service/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - buildmart-net

  delivery-service:
    build:
      context: .
      dockerfile: core/delivery-service/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - buildmart-net

  materials-bff:
    build:
      context: .
      dockerfile: bff/materials-bff/Dockerfile
    ports:
      - "8101:8101"
    environment:
      MATERIALS_CORE_URL: http://materials-service:8001
    depends_on:
      - materials-service
    networks:
      - buildmart-net

  workers-bff:
    build:
      context: .
      dockerfile: bff/workers-bff/Dockerfile
    ports:
      - "8102:8102"
    environment:
      WORKERS_CORE_URL: http://workers-service:8002
    depends_on:
      - workers-service
    networks:
      - buildmart-net

  delivery-bff:
    build:
      context: .
      dockerfile: bff/delivery-bff/Dockerfile
    ports:
      - "8103:8103"
    environment:
      DELIVERY_CORE_URL: http://delivery-service:8003
    depends_on:
      - delivery-service
    networks:
      - buildmart-net

  gateway:
    build:
      context: .
      dockerfile: bff/gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      MATERIALS_BFF_URL: http://materials-bff:8101
      WORKERS_BFF_URL: http://workers-bff:8102
      DELIVERY_BFF_URL: http://delivery-bff:8103
    depends_on:
      - materials-bff
      - workers-bff
      - delivery-bff
    networks:
      - buildmart-net

networks:
  buildmart-net:
    driver: bridge
