version: "3.8"

services:
  buildmart-materials:
    build:
      context: ./core
      dockerfile: buildmart-materials/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - buildmart-net

  buildmart-workers:
    build:
      context: ./core
      dockerfile: buildmart-workers/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - buildmart-net

  buildmart-delivery:
    build:
      context: ./core
      dockerfile: buildmart-delivery/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - buildmart-net

  buildmart-materials-bff:
    build:
      context: ./bff
      dockerfile: buildmart-materials-bff/Dockerfile
    ports:
      - "8101:8101"
    environment:
      ip_port: buildmart-materials:8001
    depends_on:
      - buildmart-materials
    networks:
      - buildmart-net

  buildmart-workers-bff:
    build:
      context: ./bff
      dockerfile: buildmart-workers-bff/Dockerfile
    ports:
      - "8102:8102"
    environment:
      ip_port: buildmart-workers:8002
    depends_on:
      - buildmart-workers
    networks:
      - buildmart-net

  buildmart-delivery-bff:
    build:
      context: ./bff
      dockerfile: buildmart-delivery-bff/Dockerfile
    ports:
      - "8103:8103"
    environment:
      ip_port: buildmart-delivery:8003
    depends_on:
      - buildmart-delivery
    networks:
      - buildmart-net

networks:
  buildmart-net:
    driver: bridge
